### ISSUE TITLE
Preview images in README

### ISSUE THREAD

**Issue by novoid** [dangom/org-thesis#1]
Hi,

This is not a bug but an improvement in order to decide for potential users whether this is something they are looking for: just like how https://latex.tugraz.at/vorlagen/allgemein is showing some images for example for https://github.com/novoid/LaTeX-KOMA-template you could add PNGs of whole pages to get an impression of the final result.

And yes, I'm going to do this for my KOMA template as well - I promise. ;-)

**Comment by dangom** [comment]
Hey novoid, thanks for reaching out! Really appreciate your blog posts and dotfiles - learned a lot from it.
The goal of this repo was not really to be a template, but more to showcase what users can do with Org mode, and how to leverage different Org functionality to compose a longer piece of work. I'm sure there are tons of other great ideas as well that could be used to improve the current setup - I'm just sharing what I learned in these past 4 years.

With that said, I've added screenshots to the REPO :). Looking forward to seeing the Hall of Fame getting populated down at your KOMA templates too!

**Comment by novoid** [comment]
Hi dangom,
Thanks for the flowers ;-)
I now understand the purpose of the repo much better. I put the task of trying it out it on my long todo list since I'm unfortunately in the position of not needing it for now.
Thanks for providing screenshots - now it's my turn - haha.
The hall of fame is a tragic story because I know for sure that probably hundreds of thesis were written using it and nobody wants to reach out to me. Well, at least LaTeX is being used ;-)
Take care!
