### ISSUE TITLE
Compiling Problems 

### ISSUE THREAD

**Issue by Simon-Says-eng** [dangom/org-thesis#8]
First, thank for your  great work. The Template looks amazing. 
i am currently running Doom Emacs on my main machine. For compiling  this thesis i used your org-init.el but i get some errors. 
Is your configuration flawlessly running?

```
emacs -nw /root/thesis/thesis/thesis.org -l /root/thesis/org-init.el
```

```
Error (use-package): Cannot load ox-extra
Error (use-package): Cannot load ox-word
Error (use-package): org-ref/:config: Symbol's function definition is void: helm-add-action-to-source
```

**Comment by dangom** [comment]
Right. I'm sorry for that, I mean to update this package and clean it up but never really get around to it.

What is happening is that in the past years there have been some changes to the way that org-mode is organized. User contributed files that were distributed by org in a package called "org-plus-contrib" are now kept in a separate repo, called "org-contrib". I just pushed a tentative fix for that.

Besides that, org-ref has been completely revamped, and my config as I used it back in 2019 when I published this repo was still on the previous version of org-ref. I've added a statement to ensure that the current code installs org-ref-2 for now. That should fix the other issue you were having.

Please let me know if you still have problems.
